name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [18.x, '20.x']
    steps:
      - uses: actions/checkout@v3
      - name: Run tests on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run test
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, '20.x']
    steps:
      - uses: actions/checkout@v3
      - name: Coverage on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
